<a href="https://colab.research.google.com/github/jaidengoerlitx/Toxic-Release-Group-4/blob/main/Midterm_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
from google.colab import drive
drive.mount('/content/drive')

%cd /content/drive/MyDrive/ColabNotebooks

import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline

import pandas as pd 
import numpy as np
import os
from tqdm import tqdm_notebook
from ipywidgets import interact_manual


import plotly.offline as py
import plotly.graph_objs as go
import plotly.figure_factory as ff
py.init_notebook_mode(connected=True)

pd.options.display.max_columns = 110
pd.options.display.max_rows = 300

import warnings
warnings.simplefilter('ignore')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/MyDrive/ColabNotebooks

In [9]:
# # Next few kernels will quickly clean the data:
# dtypes
dtypes = {
'YEAR':object,
# 'TRI_FACILITY_ID': object,
# 'FRS_ID':object,
# 'FACILITY_NAME':object,
# # 'STREET_ADDRESS':object,
'CITY':object,
'COUNTY':object,
'ST':'object',
# 'ZIP':object,
# 'BIA_CODE':'category',
# 'TRIBE':object,
'LATITUDE':object,
'LONGITUDE':object,
# 'FEDERAL_FACILITY':'category',
# 'INDUSTRY_SECTOR_CODE':'category',
'INDUSTRY_SECTOR':'category',
# 'PRIMARY_SIC':'category',
# 'SIC_2':'category',
# 'SIC_3':'category',
# 'SIC_4':'category',
# 'SIC_5':'category',
# 'SIC_6':'category',
# 'PRIMARY_NAICS':'category',
# 'NAICS_2':'category',
# 'NAICS_3':'category',
# 'NAICS_4':'category',
# 'NAICS_5':'category',
# 'NAICS_6':'category',
# 'DOC_CTRL_NUM':object,
'CHEMICAL':'object',
# 'CAS_#/COMPOUND_ID':object,
# 'SRS_ID':object,
# 'CLEAR_AIR_ACT_CHEMICAL':'category',
# 'CLASSIFICATION':'category',
# 'METAL':'category',
# 'METAL_CATEGORY':int,
# 'CARCINOGEN':'category',
# 'FORM_TYPE':'category',
'UNIT_OF_MEASURE':object,
# '5.1_FUGITIVE_AIR':object,
# '5.2_STACK_AIR':float,
# '5.3_WATER':float,
# '5.4_UNDERGROUND':float,
# '5.4.1_UNDERGROUND_CLASS_I':float,
# '5.4.2_UNDERGROUND_CLASS_II-V':float,
# '5.5.1_LANDFILLS':float,
# '5.5.1A_RCRA_C_LANDFILLS':float,
# '5.5.1B_OTHER_LANDFILLS':float,
# '5.5.2_LAND_TREATMENT':float,
# '5.5.3_SURFACE_IMPOUNDMENT':float,
# '5.5.3A_RCRA_C_SURFACE_IMP.':float,
# '5.5.3B_Other_SURFACE_IMP.':float,
# '5.5.4_OTHER_DISPOSAL':float,
# 'ON-SITE_RELEASE_TOTAL':float,
# '6.1_POTW-TRANSFERS_FOR_RELEASE':float,
# '6.1_POTW-TRANSFERS_FOR_TREATM.':float,
# '6.1_POTW-TOTAL_TRANSFERS':float,
# '6.2_M10':float,
# '6.2_M41':float,
# '6.2_M62':float,
# '6.2_M71':float,
# '6.2_M81':float,
# '6.2_M82':float,
# '6.2_M72':float,
# '6.2_M63':float,
# '6.2_M66':float,
# '6.2_M67':float,
# '6.2_M64':float,
# '6.2_M65':float,
# '6.2_M73':float,
# '6.2_M79':float,
# '6.2_M90':float,
# '6.2_M94':float,
# '6.2_M99':float,
# 'OFF-SITE_RELEASE_TOTAL':float,
# '6.2_M20':float,
# '6.2_M24':float,
# '6.2_M26':float,
# '6.2_M28':float,
# '6.2_M93':float,
# 'OFF-SITE_RECYCLED_TOTAL':float,
# '6.2_M56':float,
# '6.2_M92':float,
# 'OFF-SITE_RECOVERY_TOTAL':float,
# '6.2_M40':float,
# '6.2_M50':float,
# '6.2_M54':float,
# '6.2_M61':float,
# '6.2_M69':float,
# '6.2_M95':float,
# 'OFF-SITE_TREATED_TOTAL':float,
'TOTAL_RELEASES':object,
# '8.1_RELEASES':object,
# '8.1A_ON-SITE_CONTAINED_REL.':float,
# '8.1B_ON-SITE_OTHER_RELEASES':float,
# '8.1C_OFF-SITE_CONTAINED_REL.':float,
# '8.1D_OFF-SITE_OTHER_RELEASES':float,
# '8.2_ENERGY_RECOVERY_ON-SITE':float,
# '8.3_ENERGY_RECOVERY_OFF-SITE':float,
# '8.4_RECYCLING_ON-SITE':float,
# ' 8.5_RECYCLING_OFF-SITE':float,
# '8.6_TREATMENT_ON-SITE':float,
# # '8.7_TREATMENT_OFF-SITE':float,
# 'PROD._WASTE_(8.1_THRU_8.7)':float
# '8.8_ONE-TIME_RELEASE':float,
# 'PROD_RATIO_OR_ACTIVITY':object,
# '8.9_PRODUCTION_RATIO':float,
# 'PARENT_COMPANY_NAME':object,
# 'PARENT_COMPANY_DB_NUMBER':object,
}

In [10]:
data_1 = pd.read_csv('basic_data_files.csv', nrows=2548770, low_memory=True, dtype=dtypes, usecols=dtypes.keys())
data_2 = pd.read_csv('basic_data_files.csv', skiprows=2548771, low_memory=True, dtype=dtypes, usecols=dtypes.keys())

data_clean = data_1.append(data_2, ignore_index=True)
data_clean = data_clean.drop(index=data_clean[data_clean.YEAR == 'YEAR'].index).reset_index(drop=True)

# redefine data types to speed up manipulation:
dtypes = {'YEAR': int, 'ST': 'category', 'COUNTY': 'category', 'CITY': 'category', 'CHEMICAL':'category', 'TOTAL_RELEASES': float,
         'LATITUDE': float, 'LONGITUDE': float, 'INDUSTRY_SECTOR':'category'}
data = data_clean.astype(dtypes)

# Toxic Dataset

In [11]:
data.head()

,YEAR,CITY,COUNTY,ST,LATITUDE,LONGITUDE,INDUSTRY_SECTOR,CHEMICAL,UNIT_OF_MEASURE,TOTAL_RELEASES
0,2016,NEW CARLISLE,ST JOSEPH,IN,41.693392,-86.455176,Fabricated Metals,CHROMIUM COMPOUNDS(EXCEPT CHROMITE ORE MINED I...,Pounds,1170.4108
1,2016,NEWBURYPORT,ESSEX,MA,42.796400,-70.890440,Chemicals,CERTAIN GLYCOL ETHERS,Pounds,18.0000
2,2016,WOOSTER,WAYNE,OH,40.784710,-81.939580,Food,ZINC COMPOUNDS,Pounds,0.0000
3,2016,NEW BEDFORD,BRISTOL,MA,41.725430,-70.955170,Miscellaneous Manufacturing,DIISOCYANATES,Pounds,0.0000
4,2016,FOREST PARK,CLAYTON,GA,33.627222,-84.386839,Chemicals,CERTAIN GLYCOL ETHERS,Pounds,50.0000